language: python
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
install:
  - sed -ie "s#test-plone-4.x.cfg#test-plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - virtualenv --no-site-packages --no-setuptools .
  - bin/python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script: bin/test
