language: python
python: 3.8
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
- PLONE_VERSION=5.3
matrix:
  fast_finish: true
install:
- pip install -f requirements.txt
- bin/buildout annotate
- bin/buildout -Nq
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
